version: "3.7"

services:
  interface:
    build: 
      context: interface
      dockerfile: Dockerfile
    container_name: interface
    ports:
      - 8501:8501
    depends_on:
      - api
    restart: unless-stopped
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 80:80
    restart: unless-stopped
